const defaultProducts = [
  { id: 1, name: 'Ritual Matcha Set', category: 'Wellness', price: 34, description: 'A quiet moment in a cup.', image: 'https://images.unsplash.com/photo-1515823662972-da6c7d2f738f?auto=format&fit=crop&w=700&q=80', tag: 'Best seller' },
  { id: 2, name: 'Ripple Glass', category: 'Home', price: 18, description: 'Hand-finished amber glass.', image: 'https://images.unsplash.com/photo-1565193298357-c1e8be8f4c70?auto=format&fit=crop&w=700&q=80', tag: 'New' },
  { id: 3, name: 'Soft Focus Notebook', category: 'Desk', price: 22, description: 'For loose thoughts and bright ideas.', image: 'https://images.unsplash.com/photo-1531346878377-a5be20888e57?auto=format&fit=crop&w=700&q=80', tag: '' },
  { id: 4, name: 'Sunday Incense', category: 'Wellness', price: 16, description: 'Cedar, sage, and a slow exhale.', image: 'https://images.unsplash.com/photo-1603006905003-be475563bc59?auto=format&fit=crop&w=700&q=80', tag: 'Limited' },
  { id: 5, name: 'Arc Desk Lamp', category: 'Desk', price: 58, description: 'A softer light for later nights.', image: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=700&q=80', tag: '' },
  { id: 6, name: 'Linen Table Cloth', category: 'Home', price: 42, description: 'The everyday table, dressed up.', image: 'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?auto=format&fit=crop&w=700&q=80', tag: 'New' },
  { id: 7, name: 'Morning Carafe', category: 'Home', price: 29, description: 'Water, but make it beautiful.', image: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=700&q=80', tag: '' },
  { id: 8, name: 'Mini Desk Tray', category: 'Desk', price: 24, description: 'A home for the bits and pieces.', image: 'https://images.unsplash.com/photo-1494438639946-1ebd1d20bf85?auto=format&fit=crop&w=700&q=80', tag: '' }
];
let products = JSON.parse(localStorage.getItem('quickcart-products')) || defaultProducts;
let cart = JSON.parse(localStorage.getItem('quickcart-cart')) || [];
let activeFilter = 'All', discountRate = 0;
const $ = s => document.querySelector(s); const money = n => `$${Number(n).toFixed(2)}`;
document.addEventListener('error', event => { const image = event.target; if (image.tagName === 'IMG' && !image.dataset.fallback) { image.dataset.fallback = 'true'; image.src = 'assets/product-fallback.svg'; } }, true);
function persist(){localStorage.setItem('quickcart-products', JSON.stringify(products));localStorage.setItem('quickcart-cart', JSON.stringify(cart));}
function renderProducts(){const list=activeFilter==='All'?products:products.filter(p=>p.category===activeFilter);$('#products-grid').innerHTML=list.map(p=>`<article class="product-card"><div class="product-image"><img src="${p.image}" alt="${p.name}">${p.tag?`<span class="product-tag">${p.tag}</span>`:''}<button class="quick-add" data-add="${p.id}" aria-label="Add ${p.name} to cart">+</button></div><div class="product-info"><div><h3>${p.name}</h3><p>${p.description}</p></div><span class="product-price">${money(p.price)}</span></div></article>`).join('') || '<p>No products in this category yet.</p>';}
function cartDetails(){return cart.map(i=>({...i,product:products.find(p=>p.id===i.id)})).filter(i=>i.product)}
function renderCart(){const items=cartDetails();const count=items.reduce((s,i)=>s+i.qty,0);const sub=items.reduce((s,i)=>s+i.product.price*i.qty,0);const discount=sub*discountRate; $('#cart-count').textContent=count;$('#drawer-count').textContent=count;$('#cart-items').innerHTML=items.length?items.map(i=>`<div class="cart-item"><img src="${i.product.image}" alt="${i.product.name}"><div><h3>${i.product.name}</h3><p>${money(i.product.price)}</p><div class="quantity"><button data-qty="${i.id}" data-change="-1">−</button><span>${i.qty}</span><button data-qty="${i.id}" data-change="1">+</button></div></div><button class="remove" data-remove="${i.id}" aria-label="Remove ${i.product.name}">×</button></div>`).join(''):'<div class="empty-cart"><b>Your bag is waiting.</b>Find a small thing you’ll love.</div>';$('#subtotal').textContent=money(sub);$('#discount').textContent='−'+money(discount);$('#total').textContent=money(sub-discount);$('#checkout-total').textContent=money(sub-discount);$('#discount-row').classList.toggle('hidden',!discount);persist();}
function addToCart(id){const item=cart.find(i=>i.id===id);item?item.qty++:cart.push({id,qty:1});renderCart();showToast('Added to your bag');}
function showToast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200)}
function toggleCart(open){$('#cart-drawer').classList.toggle('open',open);$('#overlay').classList.toggle('visible',open);$('#cart-drawer').setAttribute('aria-hidden',!open)}
function openModal(id){$('#'+id).classList.add('open');$('#'+id).setAttribute('aria-hidden','false')}function closeModal(id){$('#'+id).classList.remove('open');$('#'+id).setAttribute('aria-hidden','true')}
function renderAdmin(){ $('#admin-product-count').textContent=`(${products.length})`; $('#admin-product-list').innerHTML=products.map(p=>`<div class="admin-product"><img src="${p.image}" alt=""><div><b>${p.name}</b><small>${p.category} · ${money(p.price)}</small></div><div class="admin-actions"><button data-edit="${p.id}">Edit</button><button class="delete" data-delete="${p.id}">Delete</button></div></div>`).join('')}
function resetProductForm(){ $('#product-form').reset();$('#product-id').value='';$('#form-title').textContent='Add a product';$('#save-product').textContent='Add product →';$('#cancel-edit').classList.add('hidden');}
document.addEventListener('click', e=>{const add=e.target.closest('[data-add]');if(add)addToCart(+add.dataset.add);const qty=e.target.closest('[data-qty]');if(qty){const i=cart.find(x=>x.id===+qty.dataset.qty);i.qty+=+qty.dataset.change;if(i.qty<1)cart=cart.filter(x=>x!==i);renderCart()}const remove=e.target.closest('[data-remove]');if(remove){cart=cart.filter(x=>x.id!==+remove.dataset.remove);renderCart()}const edit=e.target.closest('[data-edit]');if(edit){const p=products.find(x=>x.id===+edit.dataset.edit);$('#product-id').value=p.id;$('#product-name').value=p.name;$('#product-price').value=p.price;$('#product-category').value=p.category;$('#product-image').value=p.image;$('#product-description').value=p.description;$('#form-title').textContent='Edit product';$('#save-product').textContent='Save changes →';$('#cancel-edit').classList.remove('hidden');}const del=e.target.closest('[data-delete]');if(del){const p=products.find(x=>x.id===+del.dataset.delete);if(confirm(`Remove “${p.name}” from the collection?`)){products=products.filter(x=>x.id!==p.id);cart=cart.filter(x=>x.id!==p.id);persist();renderProducts();renderCart();renderAdmin();}}const close=e.target.closest('[data-close]');if(close)closeModal(close.dataset.close);});
$('#cart-button').onclick=()=>toggleCart(true);$('#close-cart').onclick=()=>toggleCart(false);$('#overlay').onclick=()=>toggleCart(false);$('#mobile-menu').onclick=()=>$('#main-nav').classList.toggle('open');
document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{activeFilter=b.dataset.filter;document.querySelectorAll('.filter').forEach(x=>x.classList.toggle('active',x===b));renderProducts()});
$('#apply-coupon').onclick=()=>{const code=$('#coupon-input').value.trim().toUpperCase();if(code==='HELLO10'||code==='QUICK15'){discountRate=code==='QUICK15'?.15:.1;$('#coupon-message').textContent=`${Math.round(discountRate*100)}% discount applied — lovely.`;renderCart()}else{$('#coupon-message').textContent='Try HELLO10 or QUICK15.';discountRate=0;renderCart()}};
$('#admin-link').onclick=e=>{e.preventDefault();if(localStorage.getItem('quickcart-admin')==='true'){renderAdmin();openModal('admin-modal')}else openModal('auth-modal')};
$('#login-form').onsubmit=e=>{e.preventDefault();if($('#login-email').value==='mukesh@quickcart.com'&&$('#login-password').value==='mukesh123'){localStorage.setItem('quickcart-admin','true');closeModal('auth-modal');renderAdmin();openModal('admin-modal')}else $('#login-error').textContent='That email or password doesn’t match.'};
$('#logout').onclick=()=>{localStorage.removeItem('quickcart-admin');closeModal('admin-modal');showToast('Signed out of Studio')};
$('#cancel-edit').onclick=resetProductForm;
const readImageFile = file => new Promise((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(reader.result); reader.onerror = reject; reader.readAsDataURL(file); });
$('#product-form').onsubmit=async e=>{e.preventDefault();const id=+$('#product-id').value;const upload=$('#product-upload').files[0];let image=$('#product-image').value.trim();if(upload){if(upload.size>100*1024*1024)return showToast('Please choose an image under 100 MB.');image=await readImageFile(upload)}if(!image)return showToast('Add an image path, URL, or upload a file.');const p={id:id||Date.now(),name:$('#product-name').value.trim(),price:+$('#product-price').value,category:$('#product-category').value,image,description:$('#product-description').value.trim(),tag:id?(products.find(x=>x.id===id).tag||''):'New'};if(id)products=products.map(x=>x.id===id?p:x);else products.unshift(p);persist();renderProducts();renderAdmin();resetProductForm();showToast(id?'Product updated':'Product added to collection')};
$('#checkout-button').onclick=()=>{if(!cart.length)return showToast('Your bag is still empty');toggleCart(false);openModal('checkout-modal')};
$('#checkout-form').onsubmit=e=>{e.preventDefault();cart=[];discountRate=0;renderCart();closeModal('checkout-modal');openModal('success-modal');e.target.reset()};
$('#newsletter-form').onsubmit=e=>{e.preventDefault();e.target.reset();showToast('You’re on the list — welcome.')};
renderProducts();renderCart();
